TrajectoryPlannerROS:
  #速度限制
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4
  #加速度限制
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  #完整的机器人
  holonomic_robot: false