local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: true
#将“rolling_window”参数设置为true，意味着随着机器人在现实世界里移动，代价地图会保持以机器人为中心。
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05